name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # runs at midnight every day
  workflow_dispatch:

jobs:
  generate:
    name: generate animation
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: DeepakNS003
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push the generated snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
